[core]
#shell=/usr/lib/syna-desktop-shell.so
idle-time=0
require-input=false

[shell]
#client=/usr/bin/syna-desktop-shell
#background-image=/usr/share/syna-weston-desktop/astra.png
#background-type=scale
#clock-format=none
#panel-color=0xC0C0C0C0
#panel-position=bottom
#img-panel=on
#custom-image=/usr/share/syna-weston-desktop/qr.png
#binding-modifier=alt
panel-position=none

[output]
name=DPI-1
mode=800x480@60.0
transform=rotate-270
[terminal]
term=vt100

[launcher]
icon=/usr/share/syna-weston-desktop/terminal.png
path=/usr/bin/weston-terminal
displayname=Terminal

[launcher]
icon=/usr/share/syna-weston-desktop/browser.png
path=XDG_RUNTIME_DIR=/var/run/user/0 WAYLAND_DISPLAY=wayland-1 QT_QPA_PLATFORM=wayland CHROME_USER_DATA_DIR=/home/root/chromium_data/ /usr/bin/chromium --no-sandbox --alsa-output-device=hw:0,0 --restore-last-session
displayname=Chromium

[launcher]
icon=/usr/share/syna-weston-desktop/applications.png
path=XDG_RUNTIME_DIR=/var/run/user/0 WAYLAND_DISPLAY=wayland-1 QT_QPA_PLATFORM=wayland /usr/bin/synaexplorer --mach sl2619
displayname=Syna Explorer

[launcher]
icon=/usr/share/syna-weston-desktop/settings.png
path=XDG_RUNTIME_DIR=/var/run/user/0 WAYLAND_DISPLAY=wayland-1 QT_QPA_PLATFORM=wayland /usr/bin/syna-settings --mach sl2619
displayname=Syna Settings

[launcher]
icon=/usr/share/syna-weston-desktop/about.png
path=XDG_RUNTIME_DIR=/var/run/user/0 WAYLAND_DISPLAY=wayland-1 QT_QPA_PLATFORM=wayland /usr/bin/syna-astra-about
displayname=Syna About
